version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      # Persist data locally so you don't lose it when containers restart
      - pgdata:/var/lib/postgresql/data
      # Initialize schema + functions + sample data + views on first start
      - ./sql:/docker-entrypoint-initdb.d:ro

  api:
    build: .
    environment:
      # API connects to the db service by docker network name "db"
      DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: